my_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('content/', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('about/', views.about, name='about'),
    path('error/', views.error, name='error'),
    path('references/', views.references, name='references'),

    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/',views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/',views.product_detail, name='product_detail'),
    path('menu/<int:id>/',views.menu, name='menu'),



    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('faq/', views.faq, name='faq'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user import views

urlpatterns = (
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),
    path('deleteimage/<int:id>', views.deleteimage, name='deleteimage'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django_countries.fields import CountryField

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Yes'),
        ('False', 'No'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=50)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=50)
    smtpemail = models.CharField(blank=True, max_length=50)
    smtppassword = models.CharField(blank=True, max_length=50)
    smtpport = models.CharField(blank=True, max_length=50)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    detail = RichTextUploadingField(blank=True)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(blank=True, max_length=10, choices=STATUS)
    create_at = models.DateTimeField(blank=True, auto_now_add=True)
    update_at = models.DateTimeField(blank=True, auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10,choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(blank=True,auto_now_add=True)
    update_at = models.DateTimeField(blank=True,auto_now=True)

    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name'   :TextInput(attrs={'class': 'form-control','placeholder':'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'email'  : TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}),
            'message': TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Message','rows':'5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20,help_text='Contact phone number')
    address = models.CharField(blank=True, max_length=250)
    city = models.CharField(blank=True, max_length=20)
    country = CountryField()
    image = models.ImageField(blank=True,upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name+ ' ' +self.user.last_name + ' [' +self.user.username +'] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = "Image"


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone','address','city','country','image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'Yes'),
        ('False', 'No'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(blank=True, max_length=10, choices=STATUS)
    create_at = models.DateTimeField(blank=True, auto_now_add=True)
    update_at = models.DateTimeField(blank=True, auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, ModelForm, FileInput, Select

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
        widgets = {
            'username'   : TextInput(attrs={'class':'form-control','placeholder':'username'}),
            'email'      : EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}),
            'first_name' : TextInput(attrs={'class': 'form-control', 'placeholder': 'first_name'}),
            'last_name'  : TextInput(attrs={'class': 'form-control', 'placeholder': 'last_name'}),

        }
CITY=[
    ('Istanbul','Istanbul'),
    ('Ankara','Ankara'),
    ('Izmir','Izmir'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country','image')
        widgets = {
            'phone'     : TextInput(attrs={'class': 'form-control', 'placeholder': 'phone'}),
            'address'   : TextInput(attrs={'class': 'form-control', 'placeholder': 'address'}),
            'city'      : Select(attrs={'class': 'form-control', 'placeholder': 'city'},choices=CITY),
            'country'   : TextInput(attrs={'class': 'form-control', 'placeholder': 'country'}),
            'image'     : FileInput(attrs={'class': 'form-control', 'placeholder': 'image',}),
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from home.models import UserProfile
from product.models import Category, Comment, Menu, Product, ContentForm, ContentImageForm, Images
from user.forms import UserUpdateForm, ProfileUpdateForm


def index(request):
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user #access user session

    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'category': category,
               'profile': profile,
               'menu':menu,
               }
    return render(request,'user_profile.html',context)

def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user) #request.user is user data
        profile_form = ProfileUpdateForm(request.POST,request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Your account has been updated!')
            return redirect('/user')

    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'menu':menu,
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request,'user_update.html',context)

def change_password(request):
    if request.method== 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) #Important
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect('/user')
        else:
            messages.error(request,'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form, 'category': category
        })

@login_required(login_url='/login') #check login
def comments(request):
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user  # access user session
    comments = Comment.objects.filter(user_id=current_user.id).order_by('-id')
    context = {'category': category,
               'comments': comments,
               'menu':menu,
               }
    return render(request, 'user_comments.html', context)

@login_required(login_url='/login') #check login
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Comment Deleted :)')
    return HttpResponseRedirect('/user/comments')

@login_required(login_url='/login') #check login
def contents(request):
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user  # access user session
    contents = Product.objects.filter(user_id=current_user.id).order_by('-id')
    context = {'category': category,
               'menu':menu,
               'contents': contents,
               }
    return render(request, 'user_contents.html', context)

@login_required(login_url='/login') #check login
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES,)
        if form.is_valid():
            current_user = request.user
            data = Product() #model ile baglanti kur
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = "False"
            data.save()
            messages.success(request, 'Content Form Error:' + str(form.errors))
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request,'Content Form Error:' + str(form.errors))
            return  HttpResponseRedirect('/user/addcontent')
    else:
        category = Category.objects.all()
        form = ContentForm()
        menu = Menu.objects.all()
        context = {
            'menu': menu,
            'category': category,
            'form': form,
        }
        return render(request,'user_addcontent.html',context)

@login_required(login_url='/login') #check login
def contentedit(request,id):
    content = Product.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Content Updated Succesfully :)')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.warning(request, 'Content From Error: ' + str(form.errors))
            return HttpResponseRedirect('/user/contentedit/' + str(id))
    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ContentForm(instance=content)
        context = {
            'menu': menu,
            'category': category,
            'form': form,
        }
        return render(request, 'user_addcontent.html',context)

@login_required(login_url='/login') #check login
def contentdelete(request,id):
    current_user = request.user
    Product.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Content deleted..')
    return HttpResponseRedirect('/user/contents')


def contentaddimage(request,id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST,request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.content_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request,'Your image has been successfully uploaded :)')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request,'Form Error:' +str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        content = Product.objects.get(id=id)
        images = Images.objects.filter(content_id=id)
        form = ContentImageForm()
        context = {
            'content':content,
            'images':images,
            'form':form,
        }
        return render(request,'content_gallery.html',context)


@login_required(login_url='/login') #check login
def deleteimage(request,id):
    lasturl = request.META.get('HTTP_REFERER')
    Images.objects.filter(id=id).delete()
    messages.warning(request,'Your image is deleted successfully!')
    return HttpResponseRedirect(lasturl)

user/templates/change_password.html
{% extends 'homebase.html' %}

{% block title %} User Profile - {{ profile.user_name }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block content %}


    <!-- === BEGIN CONTENT === -->
    <div id="content">
        <div class="container background-white">
            <div class="row margin-vert-10">
                <!-- Side Column -->
                <div class="col-md-3">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">User Panel</h1>
                        </div>
                    </div>
                    {% include "user_panel.html" %}
                </div>
                <!-- Main Column -->
                <div class="col-md-9">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">Change Password</h1>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">

                            {% if messages %}
                                {% for message in messages %}
                                    <div style="color: #d43f3a; font-size: medium">
                                        {{ message|safe }}
                                    </div>
                                {% endfor %}
                            {% endif %}

                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}
                                    <p>
                                        {{ field.label_tag }}<br>

                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </p>
                                {% endfor %}
                                <button class="btn-primary" type="submit">Save Changes</button>
                            </form>

                        </div>
                    </div>
                </div>
                <!-- End Main Column -->
            </div>
        </div>
    </div>
    <!-- === END CONTENT === -->


{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    table th {
        background-color: #a089ff;
        color: white;
    }
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
    input[type=file], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }


    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    input[type=submit]:hover {
        background-color: #45a049;
    }

    a {
        width: 100%;
        background-color: #a089ff;
        color: white;
        padding: 20px 20px;
        margin: 5px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    a:hover {
        background-color: #6a64ff;
    }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>
<body>
<h2>{{ content.title }}</h2>
</body>
<hr>
</html>
{% if messages %}
    {% for message in messages %}
        <div style="color: #0dd44e; font-size: medium">
            {{ message|safe }}<br><br>
        </div>
    {% endfor %}
{% endif %}

<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="content_id" id="id_content_id" value="{{ content.id }}">
        <label for="id_title">Title : </label>
        <input type="text" name="title" placeholder="Write your image title" maxlength="50" id="id_title">
        <label for="id_image">Image : </label>
        <input type="file" name="image" placeholder="image" accept="image/*" id="id_image">
        <input type="submit"></button>
    </form>
</div>
<hr>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <h2 style="text-align: center">Yüklenen Fotoğraflar</h2>
        <thead>
        <tr>
            <th>Title</th>
            <th>Image</th>
            <th>Button</th>
        </tr>
        </thead>
        <tbody>
        {% for rs in images %}
            <tr>
                <td> {{ rs.title }}</td>
                <td><img src="{{ rs.image.url }}" height="200" width="300"></td>
                <td>
                    <a href="/user/deleteimage/{{ rs.id }}" onclick="return confirm('Image will be delete are your sure?')">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

user/templates/user_addcontent.html
{% extends 'homebase.html' %}

{% block title %} Form AddContent - {{ profile.user_name }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}

    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />

    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock %}

{% block content %}


    <!-- === BEGIN CONTENT === -->
    <div id="content">
        <div class="container background-white">
            <div class="row margin-vert-10">
                <!-- Side Column -->
                <div class="col-md-2">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">User Panel</h1>
                        </div>
                    </div>
                    {% include "user_panel.html" %}
                </div>
                <!-- Main Column -->
                <div class="col-md-10">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">ADD CONTENT </h1>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ form.media}}
                                    {{ form.as_p }}
                                </fieldset>
                                <div class="form-group">
                                    <button class="btn-primary" type="submit">SAVE</button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
                <!-- End Main Column -->
            </div>
        </div>
    </div>
    <!-- === END CONTENT === -->


{% endblock %}

user/templates/user_comments.html
{% extends 'homebase.html' %}

{% block title %} User COMMENTS {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}


    <!-- === BEGIN CONTENT === -->
    <div id="content">
        <div class="container background-white">
            <div class="row margin-vert-10">
                <!-- Side Column -->
                <div class="col-md-2">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">User Panel</h1>
                        </div>
                    </div>
                    {% include "user_panel.html" %}
                </div>
                <!-- Main Column -->
                <div class="col-md-10">
                    <!-- Recent Posts -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">User Comments </h1>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div style="color: #0dd44e; font-size: medium">
                                        {{ message|safe }}<br><br>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Subject</th>
                                        <th>Comment</th>
                                        <th>Status</th>
                                        <th>Date</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for rs in comments %}
                                        <tr>
                                            <td>
                                                <a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">
                                                    <b>{{ rs.product.title }} </b></a>
                                            </td>
                                            <td>{{ rs.subject }}</td>
                                            <td>{{ rs.comment }}</td>
                                            <td>{{ rs.status }}</td>
                                            <td>{{ rs.create_at }}</td>
                                            <td>
                                                <a class="btn-violet" style="padding: 5px;border-radius: 10px" href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Comment will be delete are your sure?')">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Main Column -->
            </div>
        </div>
    </div>
    <!-- === END CONTENT === -->


{% endblock %}

user/templates/user_panel.html
<!-- === BEGIN CONTENT === -->

<!-- Side Column -->
<div class="col-md-12">
    <!-- Recent Posts -->
    <div class="panel panel-default" style="margin-left: -20px;margin-right: -20px">
        <div class="panel-body">
            <ul class="posts-list margin-top-10">
                <li>
                    <div class="recent-post">
                        <a href="/user">My Profile</a>
                        <br>
                        <span class="recent-post-date">
                                                    May 30, 2020
                                                </span>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <div class="recent-post">
                        <a href="/user/contents" >My Contents</a>
                        <br>
                        <span class="recent-post-date">
                                                    May 28, 2020
                                                </span>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <div class="recent-post">
                        <a href="">

                        </a>
                        <a href="/user/comments/">My Comments</a>
                        <br>
                        <span class="recent-post-date">
                                                    May 30, 2020
                                                </span>
                    </div>
                    <div class="clearfix"></div>
                </li>
                              <li>
                    <div class="recent-post">
                        <a href="">

                        </a>
                        <a href="/logout" >Logout</a>
                        <br>
                        <span class="recent-post-date">
                                                    July 30, 2013
                                                </span>
                    </div>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- End Side Column -->